import { Product, Category, ShopPageConfig, SortOption } from '@/types/product';
import { ProductDetail } from '@/types/productDetail';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Seeds of Change Organic Quinoa, Brown',
    slug: 'seeds-of-change-organic-quinoa-brown',
    image: '/images/thumbnail-4.jpg',
    price: 28.85,
    originalPrice: 32.8,
    discount: 12,
    rating: 4.5,
    reviewCount: 25,
    category: 'Vegetables',
    categoryId: 'vegetables',
    brand: 'NestFood',
    inStock: true,
    stockCount: 120,
    shortDescription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
  },
  {
    id: '2',
    name: 'All Natural Italian-Style Chicken Meatballs',
    slug: 'all-natural-italian-style-chicken-meatballs',
    image: '/images/thumbnail-4.jpg',
    price: 52.85,
    rating: 4.0,
    reviewCount: 18,
    category: 'Meat',
    categoryId: 'meat',
    brand: 'Stouffer',
    inStock: true,
    stockCount: 85,
    shortDescription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    isNew: true,
  },
  {
    id: '3',
    name: "Angie's Boomchickapop Sweet & Salty",
    slug: 'angies-boomchickapop-sweet-salty',
    image: '/images/thumbnail-4.jpg',
    price: 48.85,
    originalPrice: 52.8,
    discount: 7,
    rating: 4.5,
    reviewCount: 32,
    category: 'Snacks',
    categoryId: 'snacks',
    brand: "Angie's",
    inStock: true,
    stockCount: 200,
    isBestSeller: true,
  },
  {
    id: '4',
    name: 'Foster Farms Takeout Crispy Classic',
    slug: 'foster-farms-takeout-crispy-classic',
    image: '/images/thumbnail-4.jpg',
    price: 17.85,
    rating: 4.0,
    reviewCount: 15,
    category: 'Meat',
    categoryId: 'meat',
    brand: 'Foster Farms',
    inStock: true,
    stockCount: 45,
  },
  {
    id: '5',
    name: 'Blue Diamond Almonds Lightly Salted',
    slug: 'blue-diamond-almonds-lightly-salted',
    image: '/images/thumbnail-4.jpg',
    price: 23.85,
    originalPrice: 25.8,
    discount: 8,
    rating: 4.5,
    reviewCount: 48,
    category: 'Snacks',
    categoryId: 'snacks',
    brand: 'Blue Diamond',
    inStock: true,
    stockCount: 150,
  },
  {
    id: '6',
    name: 'Chobani Complete Vanilla Greek Yogurt',
    slug: 'chobani-complete-vanilla-greek-yogurt',
    image: '/images/thumbnail-4.jpg',
    price: 54.85,
    rating: 5.0,
    reviewCount: 67,
    category: 'Dairy',
    categoryId: 'dairy',
    brand: 'Chobani',
    inStock: true,
    stockCount: 90,
    isFeatured: true,
  },
  {
    id: '7',
    name: 'Canada Dry Ginger Ale - 2 L Bottle',
    slug: 'canada-dry-ginger-ale-2l-bottle',
    image: '/images/thumbnail-4.jpg',
    price: 32.85,
    originalPrice: 33.8,
    discount: 3,
    rating: 4.0,
    reviewCount: 23,
    category: 'Beverages',
    categoryId: 'beverages',
    brand: 'Canada Dry',
    inStock: false,
    stockCount: 0,
  },
  {
    id: '8',
    name: 'Encore Seafoods Stuffed Alaskan Salmon',
    slug: 'encore-seafoods-stuffed-alaskan-salmon',
    image: '/images/thumbnail-4.jpg',
    price: 35.85,
    rating: 4.5,
    reviewCount: 41,
    category: 'Seafood',
    categoryId: 'seafood',
    brand: 'Encore',
    inStock: true,
    stockCount: 30,
    isNew: true,
  },
];

export const PRODUCT_CATEGORIES: Category[] = [
  { id: 'vegetables', name: 'Vegetables', slug: 'vegetables', count: 165 },
  { id: 'fruits', name: 'Fresh Fruit', slug: 'fruits', count: 137 },
  { id: 'meat', name: 'Meat & Poultry', slug: 'meat', count: 54 },
  { id: 'seafood', name: 'Seafood', slug: 'seafood', count: 32 },
  { id: 'dairy', name: 'Milk & Dairy', slug: 'dairy', count: 98 },
  { id: 'snacks', name: 'Snacks', slug: 'snacks', count: 125 },
  { id: 'beverages', name: 'Beverages', slug: 'beverages', count: 89 },
  { id: 'bakery', name: 'Bread & Bakery', slug: 'bakery', count: 76 },
];

export const PRODUCT_BRANDS = [
  { id: 'nestfood', name: 'NestFood', count: 24 },
  { id: 'stouffer', name: 'Stouffer', count: 18 },
  { id: 'angies', name: "Angie's", count: 15 },
  { id: 'fosterfarms', name: 'Foster Farms', count: 12 },
  { id: 'bluediamond', name: 'Blue Diamond', count: 21 },
  { id: 'chobani', name: 'Chobani', count: 16 },
  { id: 'canadadry', name: 'Canada Dry', count: 9 },
  { id: 'encore', name: 'Encore', count: 11 },
];

export const SORT_OPTIONS: SortOption[] = [
  { value: 'featured', label: 'Featured' },
  { value: 'price-asc', label: 'Price: Low to High' },
  { value: 'price-desc', label: 'Price: High to Low' },
  { value: 'newest', label: 'Release Date' },
  { value: 'rating', label: 'Avg. Rating' },
];

export const SHOP_PAGE_CONFIG: ShopPageConfig = {
  sortOptions: SORT_OPTIONS,
  itemsPerPage: 12,
  defaultSort: 'featured',
};

export const PRICE_RANGE = {
  min: 0,
  max: 100,
};

export const MOCK_PRODUCT_DETAIL: ProductDetail = {
  id: '1',
  name: 'Seeds of Change Organic Quinoa, Brown',
  slug: 'seeds-of-change-organic-quinoa-brown',
  images: [
    { id: '1', url: '/images/thumbnail-3.jpg', alt: 'Product main image' },
    { id: '2', url: '/images/thumbnail-4.jpg', alt: 'Product image 2' },
    { id: '3', url: '/images/thumbnail-5.jpg', alt: 'Product image 3' },
    { id: '4', url: '/images/thumbnail-6.jpg', alt: 'Product image 4' },
    { id: '5', url: '/images/thumbnail-8.jpg', alt: 'Product image 5' },
    { id: '6', url: '/images/thumbnail-3.jpg', alt: 'Product image 6' },
  ],
  price: 28.85,
  originalPrice: 32.8,
  discount: 12,
  rating: 4.5,
  reviewCount: 25,
  shortDescription: 'Quinoa is one of the most protein-rich foods we can eat. It is a great addition to a vegan or vegetarian diet.',
  fullDescription: 'Uninhibited carnally hired played in whimpered dear gorilla koala depending and much yikes off far quetzal goodness and from for grimaced goodness unaccountably and meadowlark near unblushingly crucial scallop tightly neurotic hungrily some and dear furiously this apart.\n\nSpluttered narrowly yikes left moth in yikes bowed this that grizzly much hello on spoon-fed that alas rethought much decently richly and wow against the frequent fluidly at formidable acceptably flapped besides and much circa far over the bucolically hey precarious goldfinch mastodon goodness gnashed a jellyfish and one however because.',
  sizes: [
    { value: '50g', label: '50g', inStock: true },
    { value: '60g', label: '60g', inStock: true },
    { value: '80g', label: '80g', inStock: true },
    { value: '100g', label: '100g', inStock: false },
  ],
  info: {
    sku: 'FWM15VKT',
    category: 'Vegetables',
    tags: ['Snack', 'Organic', 'Brown'],
  },
  inStock: true,
  stockCount: 120,
  reviews: [
    {
      id: '1',
      author: 'Sienna',
      rating: 5,
      date: 'December 4, 2024',
      comment: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus, suscipit exercitationem accusantium obcaecati quos voluptate nesciunt facilis itaque modi commodi.',
      verified: true,
    },
    {
      id: '2',
      author: 'Brenna',
      rating: 4,
      date: 'December 3, 2024',
      comment: 'Great product! Really enjoyed using it.',
      verified: true,
    },
  ],
  additionalInfo: {
    'Weight': '0.5 kg',
    'Dimensions': '10 × 10 × 15 cm',
    'Color': 'Brown',
    'Material': 'Organic',
  },
  vendor: {
    name: 'NestFood',
    rating: 4.8,
    since: '2018',
  },
};